### ISSUE TITLE
CHECKLIST

### ISSUE THREAD

**Issue by justinpombrio** [justinpombrio/partial-pretty-printer#7]
Tracking things to do:

- [x] Fix Oracle.
- [x] Rename line,col -> row,col. "Line" is not a number!
- [x] Refactor NotationRef to not expose flat&indent via NotationCase.
- [x] Add IfFlat or Break (https://github.com/justinpombrio/partial-pretty-printer/issues/6). IfFlat(x, y) means "if flat then x else y". Break(txt) means IfFlat(Lit(txt), Newline). Test it.
- [x] Proofreading pass
- [x] Merge Rewrite branch
- [x] Documentation pass

**Comment by justinpombrio** [comment]
Done!!!
